---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: percona-mysql-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  project: default

  sources:
    - repoURL: https://percona.github.io/percona-helm-charts
      chart: ps-db
      targetRevision: 1.0.0
      helm:
        valueFiles:
          - $values/platform/percona-mysql-server/values.yaml
    - repoURL: https://github.com/Zolli/home-ops.git
      targetRevision: master
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: percona-mysql

  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
