---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-ca-root
  namespace: cert-manager
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "percona-mysql"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "percona-mysql"
spec:
  isCA: true
  commonName: Zolli Homelab Internal Root CA
  secretName: internal-ca-root-secret
  duration: 87600h    # 10 years
  renewBefore: 720h   # 30 days
  subject:
    organizations:
      - zolli-home
    organizationalUnits:
      - homelab
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "percona-mysql"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "percona-mysql"
  issuerRef:
    name: internal-ca-selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
